### ISSUE TITLE
checks already covered

### ISSUE THREAD

**Issue by AntoRot** [inspire-eu-validation/ats-discovery-service#4]
The checks in the tests "A.03.07.inspire.search.criteria.md" and "A.03.09.additional.search.criteria.md" are already covered by the test "A.03.01.inspire.search.attributes.md".
Remove the 2 tests.

**Comment by PeterParslow** [comment]
Proposed resolution: remove A.03.01, the summary test case, and keep the two more specifc ones. See #44
