### ISSUE TITLE
Review comment; *; GE; medium

### ISSUE THREAD

**Issue by PeterParslow** [inspire-eu-validation/ats-discovery-service#5]
The test method descriptions often are not unambiguously clear with respect to exactly what needs to the asserted. Providing the Xpath references for each selection and assertion necessary would help.

**Comment by EmidioStani** [comment]
Hello Peter, I am going to upload automatically all the issues

**Comment by PeterParslow** [comment]
Ignore - issues to be bulk uploaded.

**Comment by PeterParslow** [comment]
Thanks, Emidio – I was struggling a bit. I’m next able to take a look at this task on 1st April. I would delete my three, but the best I can do is close them.

Peter
