### ISSUE TITLE
A.02.11.xml.schema

### ISSUE THREAD

**Issue by EmidioStani** [inspire-eu-validation/ats-discovery-service#60]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Link to the XML schema (not included in the TG) should be provided to test effectively

**Comment by PeterParslow** [comment]
The namespace identifier is the normative way of identifying the schema in question; the ATS could be improved by explicitly giving this http://inspire.ec.europa.eu/schemas/common/1.0 (at present, it is listed in the Readme.md, but the test doesn't directly state which schema to use). Conveniently, the INSPIRE schema repository responds to an HTTP GET on the identifier by listing a number of files, two of which define the schema. The root file to validate against is "common.xsd".

Propose adding explicit namespace identifier; see https://github.com/inspire-eu-validation/ats-discovery-service/pull/61

**Comment by EmidioStani** [comment]
Hello Peter, thanks for solving the issue, at this stage we are not changing the ATS directly but first agree on the resolution.

**Comment by PeterParslow** [comment]
Still awaiting guidance on how to use GitHub for this!

In the meantime, I didn’t think I had changed the ATS directy; I have created a pull request – it seemed the best way to clearly state what resolution I am proposing. If you say so, I won’t do that again.

Who should I agree the resolution with? How do I notify them? I notice that the WMS issues have a variety of flags available, such as ‘ready to review’; I thought to add an appropriate flag, but I can’t see that one in the list on ATS-discovery-service.

Peter

**Comment by EmidioStani** [comment]
Hello Peter, 

for the labels we add those specified in the word document circulated.
In the case of this issue we should replace the current status with "status:in-progress" (labels can be added from issue list page here: https://github.com/inspire-eu-validation/ats-discovery-service/labels).

For the agreement on the resolution we should discuss internally, I do think that as you are the only responsible for this ATS you should be the only one having the last word on the resolution.
